name: OpenMetrics

on:
  pull_request:
    paths:
      - 'docs/specs/om/open_metrics_spec_2_0.md'

jobs:
  check-abnf:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
    - name: Set up Python 3.x
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
      with:
        python-version: "3.12.3"
    - name: Install dependencies
      run: |
        pip install -r openmetrics-spec-tests/check_openmetrics_spec_requirements.txt
    - name: Check ABNF for OpenMetrics 1.1
      run: |
        python3 openmetrics-spec-tests/check_openmetrics_spec.py docs/specs/om/open_metrics_spec_1_1.md
    - name: Check ABNF for OpenMetrics 2.0
      run: |
        python3 openmetrics-spec-tests/check_openmetrics_spec.py docs/specs/om/open_metrics_spec_2_0.md
